### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by kousu** [namgo/GDrive-Reparent#1]
1. [ ] `--delete` / scanning existing target hierarchy 
2. [ ] skip copying pre-existing files (how? does google provide a checksum? datestamp?)
3. [ ] replace requirements.txt with pyproject.toml and an automatic workflow to package
4. [ ] copy comments
